### ISSUE TITLE
This implementation does not SKIP the computation.

### ISSUE THREAD

**Issue by AlbertHuyb** [cornell-zhang/dnn-gating#1]
According to the code [here](https://github.com/cornell-zhang/dnn-gating/blob/master/utils/cg_utils.py#L163), the implementation of CGConv2d does not skip the computation of Y_r, which is proposed in your paper.

In fact, this implementation computes Y and Y_p separately, and produces the result by Y\*d+Y_p\*(1-d). This implementation increases the computation, right? So how do you actually skip and save the computation?

Thanks!

**Comment by AlbertHuyb** [comment]
Btw, did you implement **Unbiased Channel Selection with Channel Grouping** in this repo? I didn't find the code of this part.

Thanks!

**Comment by CheungBH** [comment]
> 

I think so. The actual computational time is doubled. The acceleration can only be achieved with special hardware design

**Comment by Jackie-LJQ** [comment]
> Btw, did you implement **Unbiased Channel Selection with Channel Grouping** in this repo? I didn't find the code of this part.
> 
> Thanks!

https://github.com/cornell-zhang/dnn-gating/blob/31666fadf35789b433c79eec8669a3a2df818bd4/utils/cg_utils.py#L169
I think this line implements the Channel Grouping. But it's not used in default training scripts, since the argument 'use-shuffle' in 'dnn-gating/cg-cifar10.py' is false.

**Comment by weizhehua** [comment]
Thanks a lot for your interest. First, the current implementation is only for training a CGNet model. To gain the wall-clock speedup, you need to implement the CGConv operator efficiently for your hardware backend. Second, the unbiased channel selection is achieved using the `use_group` option, where we mask the weights associated with each output channel accordingly.
> https://github.com/cornell-zhang/dnn-gating/blob/31666fadf35789b433c79eec8669a3a2df818bd4/utils/cg_utils.py#L146-L148

When we use the unbiased channel selection, we can further enable `use_shuffle`, which shuffles the input channels before each convolution, as proposed in ShuffleNet.
