### ISSUE TITLE
Question about sparsity report

### ISSUE THREAD

**Issue by selkerdawy** [cornell-zhang/dnn-gating#3]
Hello,

Great work! Thanks for sharing the code, I would like to inquire about how the sparsity is reported [https://github.com/cornell-zhang/dnn-gating/blob/master/utils/cg_utils.py#L176]. This calculates sparsity in feature maps per pixel, but as far as I know, this isn't how the filter pruning methods report FLOPs reduction. I was wondering if there is another FLOPs reduction report that calculates based on skipping the whole filter/slice or not to be comparable with filter pruning methods instead of sparsity measure? 

Also, in your paper table 4, you calculated fps with batch size 32. Would you mind sharing code to achieve actual speedup? 

Thanks!

**Comment by weizhehua** [comment]
Hi,

Thanks for your interest. The proposed channel gating is more fine-grained than traditional filter pruning methods, where the pruning decision is made for each output pixel. Based on the pruning decision, each pixel will complete or skip the computation in the conditional path.  Therefore, we can calculate the actual reduction in FLOPs using the sparsity of the feature map. As our pruning doesn't skip the entire filter/output channel, we cannot calculate the FLOP reduction in the same way as other filter pruning papers.

We obtain the actual speedup number reported in Table 4 using a specialized ASIC accelerator with a batch size of 1. I cannot share the ASIC accelerator design with you. If you are interested in the accelerator hardware, you can refer to our MICRO paper, which elaborates the details of the hardware design (https://www.csl.cornell.edu/~zhiruz/pdfs/cgnet-micro2019.pdf).

Best,
Will

**Comment by selkerdawy** [comment]
Thanks for your prompt response, I thought the granularity is kernel slice pruning not pixel-wise. I will check the paper!
